version: "3.2"

services:

  mongodb:
    image: mongo:3.6.2-jessie
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb-data:/data/db
    networks:
      - webnet
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    deploy:
      placement:
        constraints: [node.role == manager]

  worker:
    image: contract-monitor_worker:latest
    ports:
      - "5000:5000"
    networks:
      - webnet
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    volumes:
      - type: bind
        source: /Users/ynouri/Dropbox/Projects/contract_explorer/contract-monitor/worker
        target: /usr/src/worker

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  webnet:


volumes:
  mongodb-data:
    external:
      name: mongodb-data
